---
title: "meta_analysis"
author: "Nick_Fox"
date: "7/30/2017"
output: html_document
---

```{r}

#install.packages("metafor")

library(metafor)
```


### Single paper meta-analysis

Why would you want to do this?
  Aggregate findings - increase power of underpowered studies
  
Intro to meta analyses
  
  Meta-analyses assumes the effect sizes are independent
    one effect size per study
    
  Example
  
  Study 1 - 1 chocolate vs 5 chocolate --> happiness
  Study 2 - (1 chocolate vs 5 chocolate) x (crappy vs great) --> happiness
  
  What do we use?
    Can get all 3 effect sizes (2 from study 2, one from study 1)
    Can just take the first part of study 2 and compare to study 1 (two effect sizes total)
    

<b>Fixed Effects Meta-Analysis</b>

  Assumes that all studies have the same population effect size
    all variation we see from study to study is purely due to sampling error
    
  Average weighted by 1/variance of each effect size (aka 1/SE^2)
    More precise effect sizes get more weight
    Generally this means that larger studies get more weight
    Assumes you are not biasing the data you're putting in (creative removal of outliers can bias towards bigger effect sizes within these studies being used)
    
    Tells you the average of THESE studies
      Doesn't justify generalizing to studies outside of your sample (great for your studies on chocolate and happiness, but not the entire population)
      
<b>Random Effects Meta-Analysis</b>

Allows for the possibility that you're drawing from heterogenous population effect sizes
  (drawing from a normal distribution of effect sizes)
  
  Gives you some measures/tests of variability
  
  Weighting is a big more complicated, but same general principle applies
    1/(SE^2 + tau^2)
      tau^2 is the population variability of the effect sizes
  
  This also allows you to generalize to studies outside of your sample
    (maybe not as smart if you only have 2-4 studies)
    
<b>So which one to choose?</b>

Theoretical considerations

Power considerations

Outlier considerations
  Fixed effects is must more sensitive to outliers (either in effect size or sample size between studies...N=100 in person study vs N=3000 MTurk study)

What happens if I choose incorrectly?
  Fixed effects models can be too liberal - if you have any variability in your effect size distribution, you may be overconfident in your effect size estimate
  On the other hand, if you don't have variation in your population effect size, using a random-effects model may be too conservative
  
<b>There are tools out there!</b>

  Various R packages
  
  SPSS macro META
  
  Some shinyapps
  
  We're going to use R because it's free and we can save the code!
  
The package is called Metafor (it's installed above)
  
-----------------

Now we're opening up R studio and going to walk through some examples!

-----------------


